version: '3.8'
services:
  catalogdb:
    image: postgres
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  redis_stack:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6380:8001"
    networks:
      - catalog_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5544:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - catalog_network

volumes:
  postgres_catalog:

networks:
  catalog_network:
    driver: bridge
