version: '3.8'

services:
  catalogdb:
    image: postgres
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  redis_stack:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6380:8001"
    networks:
      - catalog_network

volumes:
  postgres_catalog:

networks:
  catalog_network:
    driver: bridge


